//
// Created by alogg on 2/16/2022.
//

#ifndef ARILOGGIACACHESIMULATOR_CPP_COMMON_H
#define ARILOGGIACACHESIMULATOR_CPP_COMMON_H
extern int CACHE_SIZE;
extern int BLOCK_SIZE;
extern int ASSOCIATIVITY;
extern bool WRITE_BACK;


#endif //ARILOGGIACACHESIMULATOR_CPP_COMMON_H
